### ISSUE TITLE
web3 version 6+ support?

### ISSUE THREAD

**Issue by dyslexia** [banteg/multicall.py#79]
Hi,

Looking to use Multicall in a web3py >6.0 project. Would be great to upgrade to latest web3

**Comment by dyslexia** [comment]
Looking over other multicall libs, thread support in web3py 6+ seems to be the blocker

**Comment by janeuend** [comment]
I installed Multicall 0.7.7 (latest) ignoring dependencies with web3py 6.9.0 (latest) and it seems to run just fine. This might be as simple as updating the allowed web3py versions to include some in the 6.0+ range.

**Comment by scottincrypto** [comment]
> I installed Multicall 0.7.7 (latest) ignoring dependencies with web3py 6.9.0 (latest) and it seems to run just fine. This might be as simple as updating the allowed web3py versions to include some in the 6.0+ range.

I've done the same and have been using it production with this workaround.  I've only had a quick look, but it appears the dependency is due to eth-brownie, which is only required for dev/tests as far as I can tell. I think the path forward is to remove eth-brownie as a dependency on the tests (use web3.py as the provider instead) and web3.py >=6.0.0 might be OK without too many changes.

**Comment by godofbeans** [comment]
I just want to bump this as support for web3 v6+ would be REALLY REALLY REALLY helpful. Thanks!

**Comment by janeuend** [comment]
Bump
